#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use Config::General;


use Data::Dumper;

use lib "$FindBin::Bin/../../CAP/lib";
use CAP::Solr;

my $config_file = "$FindBin::Bin/../../CAP/cap.conf";

my $cg = Config::General->new((
    '-ConfigFile' => $config_file,
    '-AutoTrue' => 1,
));

my $config = {$cg->getall}->{solr};

my $db = CAP::Solr->new($config);

#print Dumper $db->stats_contributor();

my $stats = $db->stats_contributor();

# Output a CSV summary of documents and pages
print("Contributor,Documents,Pages\n");
foreach my $contributor (sort(keys(%{$stats->{record}}))) {
    printf(
        "%s,%d,%d\n",
        $contributor,
        ($stats->{monograph}->{$contributor} || 0) + ($stats->{issue}->{$contributor} || 0),
        ($stats->{page}->{$contributor} || 0)
    );
}
