#!/usr/bin/perl

# Compile a list of all facet values that lack code->string mappings in
# the cap.labels database. These may either be invalid/incorrect codes, or
# they may be legitimate codes that don't currently have a corresponding
# label entry.

use strict;
use warnings;
use DBI;
use FindBin;
use Config::General;

use lib "$FindBin::Bin/../../CAP/lib";
use CAP::Solr;

my $config_file = "$FindBin::Bin/../../CAP/cap.conf";
my $config = Config::General->new(('-ConfigFile' => $config_file, '-AutoTrue' => 1));
my $sconf  = {$config->getall}->{solr};
my $dbi    = {$config->getall}->{Component}->{'Model::DB'}->{connect_info};

my $solr   = CAP::Solr->new($sconf);
my $dbh    = DBI->connect($dbi->{dsn}, $dbi->{user}, $dbi->{password}) or die(DBI->errstr);
my $find   = $dbh->prepare("SELECT * FROM labels WHERE field = ? AND code = ? AND lang = ?") or die($dbh->errstr);

my $facets = $solr->facet_counts(qw(lang contributor media));

foreach my $field (qw(lang contributor media)) {
    foreach my $code (keys(%{$facets->{$field}})) {
        foreach my $lang (qw(en fr)) {
            $find->execute($field, $code, $lang);
            unless ($find->rows) {
                print("missing value for $field:$code:$lang\n");
            }
        }
    }
}

