#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use Config::General;

use lib "$FindBin::Bin/../../CAP/lib";
use CAP::Solr;

my $config_file = "$FindBin::Bin/../../CAP/cap.conf";
my $config = {Config::General->new(('-ConfigFile' => $config_file, '-AutoTrue' => 1))->getall}->{solr};

my $min_date = '1000-01-01T00:00:00.000Z';
my $max_date = '2010-10-01T00:00:00.000Z'; # FIXME: should be today's date
my $max_rows = 100;

my $solr = CAP::Solr->new($config);

my $result;

$result = $solr->search(
    { _pubmin => "[* TO $min_date]" },
    { rows => $max_rows, "sort" => "oldest", fl => ["key", "pubmin"] }
);

die("Solr query error\n") unless ($result);

#use Data::Dumper;
#print Dumper($result);

print("$result->{hits} records with publication dates on or before $min_date\n");
print("Showing oldest 100:\n") if ($result->{hits} > $max_rows);
foreach my $doc (@{$result->{documents}}) {
    print("$doc->{pubmin} : $doc->{key}\n");
}

$result = $solr->search(
    { _pubmax => "[$max_date TO *]" },
    { rows => $max_rows, "sort" => "newest", fl => ["key", "pubmax"] }
);
print("$result->{hits} records with publication dates on or after $max_date\n");
print("Showing newest 100:\n") if ($result->{hits} > $max_rows);
foreach my $doc (@{$result->{documents}}) {
    print("$doc->{pubmax} : $doc->{key}\n");
}
