version: "3"

services:
  cap-apache:
    build: apache/.
    image: cap-apache:latest
    container_name: cap-apache
    # If you want to keep the Apache logs, mount the volume externally
    # volumes:
    #   - "./apachelogs:/usr/local/apache2/logs"
    environment:
      - CDNHOSTPORT=gouda.tor.c7a.ca:5984
    ports:
      - "80:80"
  cap:
    build: CAP/.
    image: cap:latest
    container_name: cap
    # Default LOGFILENAME points to /var/log/cap/
    # This must be writeable to uid 1115 (cihm)
    #volumes:
    #   - /var/log/cap/:/var/log/cap/
  cap-redis:
    image: redis:4.0.14-alpine3.10
    container_name: cap-redis
    command: ["redis-server", "--appendonly", "yes"]
    # Depending on where docker containers are stored, volumes may be faster
    # volumes:
    #   - /opt/cap-redis:/data
