#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use File::Glob qw(:glob);
use XML::LibXML;

# University of British Columbia
# CONTENTdm OAI metadata
# http://angel.library.ubc.ca/cgi-bin/oai.exe
# http://cdm15126.contentdm.oclc.org/cgi-bin/oai.exe


my $CONTRIBUTOR = 'bvau';
my $XSL  = 'bvau';
my $ROOT = '/cihm/collections/cmr/bvau';
my $CMR  = '/cihm/collections/cmr-tools';
my $SCHEMA = "$CMR/cmr.xsd";

foreach my $dir (@ARGV) {
    my $data = join('/', $ROOT, $dir, 'data');
    my $src  = join('/', $ROOT, $dir, 'data/src');

    # Make sure the collection directory exists.
    -d $src or die("Source directory '$src' does not exist");

    print("Processing collection in: $src\n");

    # Process the oai_dc records
    foreach my $file (bsd_glob("$src/*.xml")) {
        print("Processing OAI Dublin Core file: $file\n");
        my $outfile = join('/', $data, basename($file));
        #die("Quitting due to errors. Exit code: $?") if (system("$CMR/cmr", '-dump', $XSL, $file, $outfile));
        die("Quitting due to errors. Exit code: $?") if (system("$CMR/cmr", $XSL, $file, $outfile));
    }

}
