#!/usr/bin/perl
use XML::LibXML;

my $sfs = '+';
my $fs = '|';

my $record_count = 0;
my $xml = XML::LibXML::Document->new("1.0", "UTF-8");
my $set = $xml->createElement('set');
$xml->setDocumentElement($set);

while (my $line = <STDIN>) {
    warn("Record: " . ++$record_count . "\n");
    chomp($line);
    my $record = $xml->createElement('record');
    my @fields = split(/\Q$fs\E/, $line);
    for (my $i = 0; $i < @fields; ++$i) {
        my @subfields = ();
        if ($sfs) {
            @subfields = split(/\Q$sfs\E/, $fields[$i]);
        }
        else {
            @subfields = ($fields[$i]);
        }
        foreach my $content (@subfields) {
            $content =~ s/^\s+//;
            $content =~ s/^\s+$//;
            $content =~ s/^\s+/ /g;
            if ($content) {
                my $field = $xml->createElement('field');
                $field->setAttribute('i', $i);
                $field->appendChild($xml->createTextNode($content));
                $record->appendChild($field);
            }
        }
    }
    $set->appendChild($record);
}

print $xml->toString(1);
