#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin . "/.." ;
use CIHM::CMR::Archive;

foreach my $root (@ARGV) {
    print "$root\n";
    foreach my $archive(find_archives($root)) {
        print "$archive\n";
    }
}
