#!/usr/bin/perl
use strict;
use warnings;
use File::Glob qw(:glob);
use XML::LibXML;

# Simon Fraser University/Multicultural Canada documents
# Supplied are CMR records.


my $CONTRIBUTOR = 'sfu';
my $ROOT = '/cihm/collections/cmr/sfu';
my $CMR  = '/cihm/collections/cmr-tools';
my $SCHEMA = "$CMR/cmr.xsd";

my $log = "./fail.log";
open(FAIL, ">>$log") or die("Cannot open $log for appending: $!\n");

foreach my $dir (@ARGV) {
    my $data = join('/', $ROOT, $dir, 'data');

    # Make sure the collection directory exists.
    unless (-d $data) {
         warn("Collection directory '$data' does not exist\n");
         print(FAIL "$data: no such directory\n");
    }

    print("Processing collection in: $dir\n");

    # Verify each file to ensure it is valid and contains the correct
    # contributor.
    my $schema = XML::LibXML::Schema->new( location => $SCHEMA );
    foreach my $record (bsd_glob("$data/*.xml")) {
        my $cmr = XML::LibXML->new()->parse_file($record);
        eval { $schema->validate($cmr) };
        if ($@) {
            warn ("$record does not validate: $@");
            print(FAIL "$record: does not validate\n");
        }
        foreach my $contributor ($cmr->findnodes('/recordset/record/contributor')) {
            my $code = $contributor->findvalue('.');
            warn("$record contains improper contributor code '$code'\n") unless ($code eq $CONTRIBUTOR);
        }
        print "$record: ok\n";
    }
}
