=head1 NAME

Install - Notes on installing, configuring, and upgrading

=head1 PREPARATION

Some notes about preparing your system for installation.

=head2 Mac OS (Snow Leopard)

Download and install MySQL. You don't need to set a root password. You
probably want to install the preference panel item and set MySQL to start
at boot time.

Install XCode: we will need it for make and possibly some other tools.

Run CPAN and issue the following commands (optional, but recommended):

=over 4

=item install YAML

=item install CPAN::Bundle

=item item o conf prerequisites_policy follow

=item o conf build_requires_install_policy yes

=item o conf commit

=back

Run the script I<bin/cpan-setup> to install the needed CPAN modules.

Install MacPorts and then install the following:

shared-mime-info

netpbm

This will install, among other things, Perl 5.8, which we don't want,
so we should remove execute permissions from that binary.

Install mod_perl

=head1 INSTALLATION

Unpack archive

Run database creation script

Create admin account (manually)

Run test server

Deploy using apache, etc.

=head2 Apache Deployment

Install the Perl module Catalyst::Engine::Apache

=head2 UPGRADES

To upgrade the system, unpack the tar archive and create a symlink from
cap to the new directory. Copy over your old configuration file (after
amending it to include any new configuration options) if desired. You may
also want to copy over your templates.
