=head1 NAME

Readme - general development notes

=head1 DESCRIPTION

This section provides some overal general development notes

=head1 TODO

=head2 Catalyst Application

=item templates

change pimg references to file calls

=item /admin/*/docs

try to get pod2html to link documents together properly

=head2 DFAIT Portal

=head2 Solr

=head2 Documentation

standardize format for documentation

include license, author, copyright information

=cut
