package CAP::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

#__PACKAGE__->config(
    #schema_class => 'CAP::Schema',
    
    #connect_info => {
    #    dsn => 'dbi:mysql:cap',
    #    user => 'cap',
    #    password => '',
    #},

#);

=head1 NAME

CAP::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CAP>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CAP::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

William Wueppelmann

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
