#!/usr/bin/perl
use strict;
use warnings;

=head1 export - export data from the CAP database in JSON format.

=head1 Usage

import FILE

=cut

use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use CAP;
use CAP::Util::Export;

my $file = shift(@ARGV) || die("Missing import file name");
my $c = CAP->new();
my $e = new CAP::Util::Export(c => $c);
$e->import_data($file);

