FROM perl:5.24.2

RUN groupadd -g 1115 cihm && useradd -u 1015 -g cihm -m cihm && \
    cpanm -n Carton && mkdir -p /opt/cap && ln -s cap/log4perl.conf /opt/log4perl.conf

WORKDIR /opt/cap
COPY cpanfile* /opt/cap/
RUN carton install || (cat /root/.cpanm/work/*/build.log && exit 1)
RUN echo "Now run the image and use 'docker cp container:/opt/cap/cpanfile.snapshot cpanfile.snapshot' to get the updated snapshot file"
