# This Makefile is for the CAP extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.54 (Revision: 65400) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     ABSTRACT => q[Catalyst based application]
#     AUTHOR => q[William Wueppelmann <william.wueppelmann@canadiana.ca>]
#     DIR => []
#     DISTNAME => q[CAP]
#     EXE_FILES => []
#     NAME => q[CAP]
#     NO_META => q[1]
#     PL_FILES => {  }
#     PREREQ_PM => { parent=>q[0], Catalyst::Plugin::Static::Simple=>q[0], Catalyst::Plugin::ConfigLoader=>q[0], ExtUtils::MakeMaker=>q[6.42], Catalyst::Plugin::Session=>q[0], Catalyst::Action::RenderView=>q[0], Catalyst::Plugin::Session::Store::FastMmap=>q[0], Catalyst::Plugin::Session::State::Cookie=>q[0], Catalyst::Plugin::Authentication=>q[0], Catalyst::Plugin::Authorization::Roles=>q[0], Config::General=>q[0], Catalyst::Runtime=>q[5.7015] }
#     VERSION => q[undef]
#     dist => { PREOP=>q[$(PERL) -I. "-MModule::Install::Admin" -e "dist_preop(q($(DISTVNAME)))"] }
#     realclean => { FILES=>q[MYMETA.yml] }
#     test => { TESTS=>q[t/01app.t t/02pod.t t/03podcoverage.t t/controller_Access-Default.t t/controller_Access-ECO.t t/controller_Admin.t t/controller_Ajax.t t/controller_File.t t/controller_Payment-PayPal.t t/controller_Search.t t/controller_User.t t/controller_View.t t/model_DB.t t/view_Ajax.t t/view_Default.t t/view_Dojo.t t/view_Mail.t t/view_Test.t] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /System/Library/Perl/5.10.0/darwin-thread-multi-2level/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = gcc-4.2
CCCDLFLAGS =  
CCDLFLAGS =  
DLEXT = bundle
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = gcc-4.2 -mmacosx-version-min=10.6
LDDLFLAGS = -arch x86_64 -arch i386 -arch ppc -bundle -undefined dynamic_lookup -L/usr/local/lib
LDFLAGS = -arch x86_64 -arch i386 -arch ppc -L/usr/local/lib
LIBC = /usr/lib/libc.dylib
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = darwin
OSVERS = 10.0
RANLIB = /usr/bin/ar s
SITELIBEXP = /Library/Perl/5.10.0
SITEARCHEXP = /Library/Perl/5.10.0/darwin-thread-multi-2level
SO = dylib
VENDORARCHEXP = /Network/Library/Perl/5.10.0/darwin-thread-multi-2level
VENDORLIBEXP = /Network/Library/Perl/5.10.0


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = CAP
NAME_SYM = CAP
VERSION = undef
VERSION_MACRO = VERSION
VERSION_SYM = undef
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = undef
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /
SITEPREFIX = /usr/local
VENDORPREFIX = /usr/local
INSTALLPRIVLIB = /Library/Perl/Updates/5.10.0
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /Library/Perl/5.10.0
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /Network/Library/Perl/5.10.0
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /Library/Perl/Updates/5.10.0/darwin-thread-multi-2level
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /Library/Perl/5.10.0/darwin-thread-multi-2level
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /Network/Library/Perl/5.10.0/darwin-thread-multi-2level
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /usr/local/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /usr/local/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /usr/local/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /usr/local/share/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /usr/local/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /usr/local/share/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /usr/local/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB =
PERL_ARCHLIB = /System/Library/Perl/5.10.0/darwin-thread-multi-2level
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /System/Library/Perl/5.10.0/darwin-thread-multi-2level/CORE
PERL = /usr/bin/perl "-Iinc"
FULLPERL = /usr/bin/perl "-Iinc"
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-Iinc" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-Iinc" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-Iinc" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /Library/Perl/Updates/5.10.0/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.54
MM_REVISION = 65400

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = CAP
BASEEXT = CAP
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = 
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/BagIt.pm \
	lib/CAP.pm \
	lib/CAP/Controller/Ajax.pm \
	lib/CAP/Controller/File.pm \
	lib/CAP/Controller/Foo.pm \
	lib/CAP/Controller/Root.pm \
	lib/CAP/Controller/View.pm \
	lib/CAP/Model/DB.pm \
	lib/CAP/Schema/Result/Collection.pm \
	lib/CAP/Schema/Result/Groups.pm \
	lib/CAP/Schema/Result/GroupsCollection.pm \
	lib/CAP/Schema/Result/Info.pm \
	lib/CAP/Schema/Result/Institution.pm \
	lib/CAP/Schema/Result/InstitutionCollection.pm \
	lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	lib/CAP/Schema/Result/Labels.pm \
	lib/CAP/Schema/Result/Promocode.pm \
	lib/CAP/Schema/Result/RequestLog.pm \
	lib/CAP/Schema/Result/Role.pm \
	lib/CAP/Schema/Result/SearchLog.pm \
	lib/CAP/Schema/Result/Sessions.pm \
	lib/CAP/Schema/Result/Subscription.pm \
	lib/CAP/Schema/Result/User.pm \
	lib/CAP/Schema/Result/UserCollection.pm \
	lib/CAP/Schema/Result/UserDocument.pm \
	lib/CAP/Schema/Result/UserGroups.pm \
	lib/CAP/Schema/Result/UserRole.pm \
	lib/CAP/Schema/ResultSet/Sessions.pm \
	lib/CAP/Solr.pm \
	lib/CAP/View/Ajax.pm \
	lib/CAP/View/Default.pm \
	lib/CAP/View/Dojo.pm \
	lib/CAP/View/Mail.pm \
	lib/CAP/View/Test.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/BagIt.pm \
	lib/CAP.pm \
	lib/CAP/Controller/Access/Default.pm \
	lib/CAP/Controller/Access/ECO.pm \
	lib/CAP/Controller/Admin.pm \
	lib/CAP/Controller/Ajax.pm \
	lib/CAP/Controller/File.pm \
	lib/CAP/Controller/Foo.pm \
	lib/CAP/Controller/Payment/PayPal.pm \
	lib/CAP/Controller/Root.pm \
	lib/CAP/Controller/Search.pm \
	lib/CAP/Controller/User.pm \
	lib/CAP/Controller/View.pm \
	lib/CAP/I18N/fr.mo \
	lib/CAP/I18N/fr.po \
	lib/CAP/I18N/gettext.sh \
	lib/CAP/Ingest.pm \
	lib/CAP/Model/DB.pm \
	lib/CAP/Schema.pm \
	lib/CAP/Schema/Result/Collection.pm \
	lib/CAP/Schema/Result/Groups.pm \
	lib/CAP/Schema/Result/GroupsCollection.pm \
	lib/CAP/Schema/Result/Info.pm \
	lib/CAP/Schema/Result/Institution.pm \
	lib/CAP/Schema/Result/InstitutionCollection.pm \
	lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	lib/CAP/Schema/Result/Labels.pm \
	lib/CAP/Schema/Result/Promocode.pm \
	lib/CAP/Schema/Result/RequestLog.pm \
	lib/CAP/Schema/Result/Role.pm \
	lib/CAP/Schema/Result/SearchLog.pm \
	lib/CAP/Schema/Result/Sessions.pm \
	lib/CAP/Schema/Result/Subscription.pm \
	lib/CAP/Schema/Result/User.pm \
	lib/CAP/Schema/Result/UserCollection.pm \
	lib/CAP/Schema/Result/UserDocument.pm \
	lib/CAP/Schema/Result/UserGroups.pm \
	lib/CAP/Schema/Result/UserRole.pm \
	lib/CAP/Schema/ResultSet/Collection.pm \
	lib/CAP/Schema/ResultSet/GroupsCollection.pm \
	lib/CAP/Schema/ResultSet/Info.pm \
	lib/CAP/Schema/ResultSet/InstitutionCollection.pm \
	lib/CAP/Schema/ResultSet/InstitutionIpaddr.pm \
	lib/CAP/Schema/ResultSet/Labels.pm \
	lib/CAP/Schema/ResultSet/Promocode.pm \
	lib/CAP/Schema/ResultSet/RequestLog.pm \
	lib/CAP/Schema/ResultSet/Role.pm \
	lib/CAP/Schema/ResultSet/SearchLog.pm \
	lib/CAP/Schema/ResultSet/Sessions.pm \
	lib/CAP/Schema/ResultSet/Subscription.pm \
	lib/CAP/Schema/ResultSet/User.pm \
	lib/CAP/Schema/ResultSet/UserCollection.pm \
	lib/CAP/Schema/ResultSet/UserDocument.pm \
	lib/CAP/Schema/ResultSet/UserGroups.pm \
	lib/CAP/Schema/ResultSet/UserRole.pm \
	lib/CAP/Solr.pm \
	lib/CAP/View/Ajax.pm \
	lib/CAP/View/Default.pm \
	lib/CAP/View/Dojo.pm \
	lib/CAP/View/Mail.pm \
	lib/CAP/View/Test.pm

PM_TO_BLIB = lib/CAP/Schema/ResultSet/InstitutionCollection.pm \
	blib/lib/CAP/Schema/ResultSet/InstitutionCollection.pm \
	lib/CAP/I18N/gettext.sh \
	blib/lib/CAP/I18N/gettext.sh \
	lib/CAP/I18N/fr.po \
	blib/lib/CAP/I18N/fr.po \
	lib/CAP/Ingest.pm \
	blib/lib/CAP/Ingest.pm \
	lib/CAP/Schema/ResultSet/GroupsCollection.pm \
	blib/lib/CAP/Schema/ResultSet/GroupsCollection.pm \
	lib/CAP/Schema/ResultSet/Role.pm \
	blib/lib/CAP/Schema/ResultSet/Role.pm \
	lib/CAP/Schema/Result/Subscription.pm \
	blib/lib/CAP/Schema/Result/Subscription.pm \
	lib/CAP/Schema/Result/Labels.pm \
	blib/lib/CAP/Schema/Result/Labels.pm \
	lib/CAP/Schema/Result/Institution.pm \
	blib/lib/CAP/Schema/Result/Institution.pm \
	lib/CAP/Controller/Ajax.pm \
	blib/lib/CAP/Controller/Ajax.pm \
	lib/CAP/Schema/ResultSet/Info.pm \
	blib/lib/CAP/Schema/ResultSet/Info.pm \
	lib/CAP/Schema/ResultSet/Subscription.pm \
	blib/lib/CAP/Schema/ResultSet/Subscription.pm \
	lib/CAP/Controller/User.pm \
	blib/lib/CAP/Controller/User.pm \
	lib/CAP/Controller/File.pm \
	blib/lib/CAP/Controller/File.pm \
	lib/CAP/Schema/Result/User.pm \
	blib/lib/CAP/Schema/Result/User.pm \
	lib/CAP/Schema/Result/UserDocument.pm \
	blib/lib/CAP/Schema/Result/UserDocument.pm \
	lib/CAP/Schema.pm \
	blib/lib/CAP/Schema.pm \
	lib/CAP/Schema/Result/RequestLog.pm \
	blib/lib/CAP/Schema/Result/RequestLog.pm \
	lib/CAP/Schema/ResultSet/UserDocument.pm \
	blib/lib/CAP/Schema/ResultSet/UserDocument.pm \
	lib/CAP/Schema/ResultSet/User.pm \
	blib/lib/CAP/Schema/ResultSet/User.pm \
	lib/CAP/Controller/Root.pm \
	blib/lib/CAP/Controller/Root.pm \
	lib/CAP/Controller/Access/ECO.pm \
	blib/lib/CAP/Controller/Access/ECO.pm \
	lib/CAP/Schema/ResultSet/RequestLog.pm \
	blib/lib/CAP/Schema/ResultSet/RequestLog.pm \
	lib/CAP/Solr.pm \
	blib/lib/CAP/Solr.pm \
	lib/CAP/View/Ajax.pm \
	blib/lib/CAP/View/Ajax.pm \
	lib/CAP/Schema/Result/UserGroups.pm \
	blib/lib/CAP/Schema/Result/UserGroups.pm \
	lib/CAP/Schema/Result/Collection.pm \
	blib/lib/CAP/Schema/Result/Collection.pm \
	lib/CAP/Schema/ResultSet/Promocode.pm \
	blib/lib/CAP/Schema/ResultSet/Promocode.pm \
	lib/CAP/Controller/Access/Default.pm \
	blib/lib/CAP/Controller/Access/Default.pm \
	lib/CAP/View/Default.pm \
	blib/lib/CAP/View/Default.pm \
	lib/CAP/Schema/Result/Role.pm \
	blib/lib/CAP/Schema/Result/Role.pm \
	lib/CAP/Schema/ResultSet/UserGroups.pm \
	blib/lib/CAP/Schema/ResultSet/UserGroups.pm \
	lib/CAP/Schema/Result/InstitutionCollection.pm \
	blib/lib/CAP/Schema/Result/InstitutionCollection.pm \
	lib/CAP/Schema/ResultSet/UserRole.pm \
	blib/lib/CAP/Schema/ResultSet/UserRole.pm \
	lib/CAP/Schema/ResultSet/UserCollection.pm \
	blib/lib/CAP/Schema/ResultSet/UserCollection.pm \
	lib/CAP/View/Test.pm \
	blib/lib/CAP/View/Test.pm \
	lib/CAP/Controller/Search.pm \
	blib/lib/CAP/Controller/Search.pm \
	lib/CAP/Controller/Admin.pm \
	blib/lib/CAP/Controller/Admin.pm \
	lib/BagIt.pm \
	blib/lib/BagIt.pm \
	lib/CAP/View/Dojo.pm \
	blib/lib/CAP/View/Dojo.pm \
	lib/CAP/Schema/Result/Sessions.pm \
	blib/lib/CAP/Schema/Result/Sessions.pm \
	lib/CAP/Schema/Result/UserRole.pm \
	blib/lib/CAP/Schema/Result/UserRole.pm \
	lib/CAP/Controller/Foo.pm \
	blib/lib/CAP/Controller/Foo.pm \
	lib/CAP.pm \
	blib/lib/CAP.pm \
	lib/CAP/Schema/Result/UserCollection.pm \
	blib/lib/CAP/Schema/Result/UserCollection.pm \
	lib/CAP/I18N/fr.mo \
	blib/lib/CAP/I18N/fr.mo \
	lib/CAP/View/Mail.pm \
	blib/lib/CAP/View/Mail.pm \
	lib/CAP/Schema/ResultSet/Labels.pm \
	blib/lib/CAP/Schema/ResultSet/Labels.pm \
	lib/CAP/Schema/ResultSet/SearchLog.pm \
	blib/lib/CAP/Schema/ResultSet/SearchLog.pm \
	lib/CAP/Schema/ResultSet/InstitutionIpaddr.pm \
	blib/lib/CAP/Schema/ResultSet/InstitutionIpaddr.pm \
	lib/CAP/Model/DB.pm \
	blib/lib/CAP/Model/DB.pm \
	lib/CAP/Schema/Result/Promocode.pm \
	blib/lib/CAP/Schema/Result/Promocode.pm \
	lib/CAP/Controller/Payment/PayPal.pm \
	blib/lib/CAP/Controller/Payment/PayPal.pm \
	lib/CAP/Schema/Result/Groups.pm \
	blib/lib/CAP/Schema/Result/Groups.pm \
	lib/CAP/Schema/Result/Info.pm \
	blib/lib/CAP/Schema/Result/Info.pm \
	lib/CAP/Schema/Result/SearchLog.pm \
	blib/lib/CAP/Schema/Result/SearchLog.pm \
	lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	blib/lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	lib/CAP/Schema/Result/GroupsCollection.pm \
	blib/lib/CAP/Schema/Result/GroupsCollection.pm \
	lib/CAP/Schema/ResultSet/Collection.pm \
	blib/lib/CAP/Schema/ResultSet/Collection.pm \
	lib/CAP/Controller/View.pm \
	blib/lib/CAP/Controller/View.pm \
	lib/CAP/Schema/ResultSet/Sessions.pm \
	blib/lib/CAP/Schema/ResultSet/Sessions.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 6.54
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = COPY_EXTENDED_ATTRIBUTES_DISABLE=1 COPYFILE_DISABLE=1 tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip --best
SUFFIX = .gz
SHAR = shar
PREOP = $(PERL) -I. "-MModule::Install::Admin" -e "dist_preop(q($(DISTVNAME)))"
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = CAP
DISTVNAME = CAP-undef


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	lib/CAP/View/Default.pm \
	lib/CAP/Schema/Result/Role.pm \
	lib/CAP/Schema/Result/InstitutionCollection.pm \
	lib/CAP/View/Test.pm \
	lib/BagIt.pm \
	lib/CAP/Schema/Result/Subscription.pm \
	lib/CAP/Schema/Result/Labels.pm \
	lib/CAP/Controller/Ajax.pm \
	lib/CAP/Schema/Result/Institution.pm \
	lib/CAP/Schema/Result/Sessions.pm \
	lib/CAP/View/Dojo.pm \
	lib/CAP/Schema/Result/UserRole.pm \
	lib/CAP/Controller/Foo.pm \
	lib/CAP/Controller/File.pm \
	lib/CAP/Schema/Result/User.pm \
	lib/CAP/Schema/Result/UserDocument.pm \
	lib/CAP.pm \
	lib/CAP/Schema/Result/RequestLog.pm \
	lib/CAP/Schema/Result/UserCollection.pm \
	lib/CAP/Controller/Root.pm \
	lib/CAP/View/Mail.pm \
	lib/CAP/Solr.pm \
	lib/CAP/Model/DB.pm \
	lib/CAP/Schema/Result/Promocode.pm \
	lib/CAP/Schema/Result/UserGroups.pm \
	lib/CAP/View/Ajax.pm \
	lib/CAP/Schema/Result/Collection.pm \
	lib/CAP/Schema/Result/Groups.pm \
	lib/CAP/Schema/Result/Info.pm \
	lib/CAP/Schema/Result/SearchLog.pm \
	lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	lib/CAP/Schema/Result/GroupsCollection.pm \
	lib/CAP/Controller/View.pm \
	lib/CAP/Schema/ResultSet/Sessions.pm
	$(NOECHO) $(POD2MAN) --section=3 --perm_rw=$(PERM_RW) \
	  lib/CAP/View/Default.pm $(INST_MAN3DIR)/CAP::View::Default.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Role.pm $(INST_MAN3DIR)/CAP::Schema::Result::Role.$(MAN3EXT) \
	  lib/CAP/Schema/Result/InstitutionCollection.pm $(INST_MAN3DIR)/CAP::Schema::Result::InstitutionCollection.$(MAN3EXT) \
	  lib/CAP/View/Test.pm $(INST_MAN3DIR)/CAP::View::Test.$(MAN3EXT) \
	  lib/BagIt.pm $(INST_MAN3DIR)/BagIt.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Subscription.pm $(INST_MAN3DIR)/CAP::Schema::Result::Subscription.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Labels.pm $(INST_MAN3DIR)/CAP::Schema::Result::Labels.$(MAN3EXT) \
	  lib/CAP/Controller/Ajax.pm $(INST_MAN3DIR)/CAP::Controller::Ajax.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Institution.pm $(INST_MAN3DIR)/CAP::Schema::Result::Institution.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Sessions.pm $(INST_MAN3DIR)/CAP::Schema::Result::Sessions.$(MAN3EXT) \
	  lib/CAP/View/Dojo.pm $(INST_MAN3DIR)/CAP::View::Dojo.$(MAN3EXT) \
	  lib/CAP/Schema/Result/UserRole.pm $(INST_MAN3DIR)/CAP::Schema::Result::UserRole.$(MAN3EXT) \
	  lib/CAP/Controller/Foo.pm $(INST_MAN3DIR)/CAP::Controller::Foo.$(MAN3EXT) \
	  lib/CAP/Controller/File.pm $(INST_MAN3DIR)/CAP::Controller::File.$(MAN3EXT) \
	  lib/CAP/Schema/Result/User.pm $(INST_MAN3DIR)/CAP::Schema::Result::User.$(MAN3EXT) \
	  lib/CAP/Schema/Result/UserDocument.pm $(INST_MAN3DIR)/CAP::Schema::Result::UserDocument.$(MAN3EXT) \
	  lib/CAP.pm $(INST_MAN3DIR)/CAP.$(MAN3EXT) \
	  lib/CAP/Schema/Result/RequestLog.pm $(INST_MAN3DIR)/CAP::Schema::Result::RequestLog.$(MAN3EXT) \
	  lib/CAP/Schema/Result/UserCollection.pm $(INST_MAN3DIR)/CAP::Schema::Result::UserCollection.$(MAN3EXT) \
	  lib/CAP/Controller/Root.pm $(INST_MAN3DIR)/CAP::Controller::Root.$(MAN3EXT) \
	  lib/CAP/View/Mail.pm $(INST_MAN3DIR)/CAP::View::Mail.$(MAN3EXT) \
	  lib/CAP/Solr.pm $(INST_MAN3DIR)/CAP::Solr.$(MAN3EXT) \
	  lib/CAP/Model/DB.pm $(INST_MAN3DIR)/CAP::Model::DB.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Promocode.pm $(INST_MAN3DIR)/CAP::Schema::Result::Promocode.$(MAN3EXT) \
	  lib/CAP/Schema/Result/UserGroups.pm $(INST_MAN3DIR)/CAP::Schema::Result::UserGroups.$(MAN3EXT) \
	  lib/CAP/View/Ajax.pm $(INST_MAN3DIR)/CAP::View::Ajax.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Collection.pm $(INST_MAN3DIR)/CAP::Schema::Result::Collection.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Groups.pm $(INST_MAN3DIR)/CAP::Schema::Result::Groups.$(MAN3EXT) \
	  lib/CAP/Schema/Result/Info.pm $(INST_MAN3DIR)/CAP::Schema::Result::Info.$(MAN3EXT) \
	  lib/CAP/Schema/Result/SearchLog.pm $(INST_MAN3DIR)/CAP::Schema::Result::SearchLog.$(MAN3EXT) \
	  lib/CAP/Schema/Result/InstitutionIpaddr.pm $(INST_MAN3DIR)/CAP::Schema::Result::InstitutionIpaddr.$(MAN3EXT) \
	  lib/CAP/Schema/Result/GroupsCollection.pm $(INST_MAN3DIR)/CAP::Schema::Result::GroupsCollection.$(MAN3EXT) \
	  lib/CAP/Controller/View.pm $(INST_MAN3DIR)/CAP::Controller::View.$(MAN3EXT) \
	  lib/CAP/Schema/ResultSet/Sessions.pm $(INST_MAN3DIR)/CAP::Schema::ResultSet::Sessions.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  $(BASEEXT).x $(BOOTSTRAP) \
	  perl$(EXE_EXT) tmon.out \
	  *$(OBJ_EXT) pm_to_blib \
	  $(INST_ARCHAUTODIR)/extralibs.ld blibdirs.ts \
	  core.[0-9][0-9][0-9][0-9][0-9] *perl.core \
	  core.*perl.*.? $(MAKE_APERL_FILE) \
	  perl $(BASEEXT).def \
	  core.[0-9][0-9][0-9] mon.out \
	  lib$(BASEEXT).def perlmain.c \
	  perl.exe so_locations \
	  $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  MYMETA.yml $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile :
	$(NOECHO) $(NOOP)


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old 



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir  
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"' --



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLARCHLIB)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLVENDORARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_vendor_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::
	$(NOECHO) $(UNINSTALL) $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::
	$(NOECHO) $(UNINSTALL) $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/01app.t t/02pod.t t/03podcoverage.t t/controller_Access-Default.t t/controller_Access-ECO.t t/controller_Admin.t t/controller_Ajax.t t/controller_File.t t/controller_Payment-PayPal.t t/controller_Search.t t/controller_User.t t/controller_View.t t/model_DB.t t/view_Ajax.t t/view_Default.t t/view_Dojo.t t/view_Mail.t t/view_Test.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE) subdirs-test

subdirs-test ::
	$(NOECHO) $(NOOP)


test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), 'inc', '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-Iinc" "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="undef">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>Catalyst based application</ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>William Wueppelmann &lt;william.wueppelmann@canadiana.ca&gt;</AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Action::RenderView" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Authentication" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Authorization::Roles" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::ConfigLoader" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Session" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Session::State::Cookie" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Session::Store::FastMmap" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Plugin::Static::Simple" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Catalyst::Runtime" VERSION="5.7015" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Config::General" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="ExtUtils::MakeMaker" VERSION="6.42" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="parent::" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="darwin-thread-multi-2level-5.10" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  lib/CAP/Schema/ResultSet/InstitutionCollection.pm blib/lib/CAP/Schema/ResultSet/InstitutionCollection.pm \
	  lib/CAP/I18N/gettext.sh blib/lib/CAP/I18N/gettext.sh \
	  lib/CAP/I18N/fr.po blib/lib/CAP/I18N/fr.po \
	  lib/CAP/Ingest.pm blib/lib/CAP/Ingest.pm \
	  lib/CAP/Schema/ResultSet/GroupsCollection.pm blib/lib/CAP/Schema/ResultSet/GroupsCollection.pm \
	  lib/CAP/Schema/ResultSet/Role.pm blib/lib/CAP/Schema/ResultSet/Role.pm \
	  lib/CAP/Schema/Result/Subscription.pm blib/lib/CAP/Schema/Result/Subscription.pm \
	  lib/CAP/Schema/Result/Labels.pm blib/lib/CAP/Schema/Result/Labels.pm \
	  lib/CAP/Schema/Result/Institution.pm blib/lib/CAP/Schema/Result/Institution.pm \
	  lib/CAP/Controller/Ajax.pm blib/lib/CAP/Controller/Ajax.pm \
	  lib/CAP/Schema/ResultSet/Info.pm blib/lib/CAP/Schema/ResultSet/Info.pm \
	  lib/CAP/Schema/ResultSet/Subscription.pm blib/lib/CAP/Schema/ResultSet/Subscription.pm \
	  lib/CAP/Controller/User.pm blib/lib/CAP/Controller/User.pm \
	  lib/CAP/Controller/File.pm blib/lib/CAP/Controller/File.pm \
	  lib/CAP/Schema/Result/User.pm blib/lib/CAP/Schema/Result/User.pm \
	  lib/CAP/Schema/Result/UserDocument.pm blib/lib/CAP/Schema/Result/UserDocument.pm \
	  lib/CAP/Schema.pm blib/lib/CAP/Schema.pm \
	  lib/CAP/Schema/Result/RequestLog.pm blib/lib/CAP/Schema/Result/RequestLog.pm \
	  lib/CAP/Schema/ResultSet/UserDocument.pm blib/lib/CAP/Schema/ResultSet/UserDocument.pm \
	  lib/CAP/Schema/ResultSet/User.pm blib/lib/CAP/Schema/ResultSet/User.pm \
	  lib/CAP/Controller/Root.pm blib/lib/CAP/Controller/Root.pm \
	  lib/CAP/Controller/Access/ECO.pm blib/lib/CAP/Controller/Access/ECO.pm \
	  lib/CAP/Schema/ResultSet/RequestLog.pm blib/lib/CAP/Schema/ResultSet/RequestLog.pm \
	  lib/CAP/Solr.pm blib/lib/CAP/Solr.pm \
	  lib/CAP/View/Ajax.pm blib/lib/CAP/View/Ajax.pm \
	  lib/CAP/Schema/Result/UserGroups.pm blib/lib/CAP/Schema/Result/UserGroups.pm \
	  lib/CAP/Schema/Result/Collection.pm blib/lib/CAP/Schema/Result/Collection.pm \
	  lib/CAP/Schema/ResultSet/Promocode.pm blib/lib/CAP/Schema/ResultSet/Promocode.pm \
	  lib/CAP/Controller/Access/Default.pm blib/lib/CAP/Controller/Access/Default.pm \
	  lib/CAP/View/Default.pm blib/lib/CAP/View/Default.pm \
	  lib/CAP/Schema/Result/Role.pm blib/lib/CAP/Schema/Result/Role.pm \
	  lib/CAP/Schema/ResultSet/UserGroups.pm blib/lib/CAP/Schema/ResultSet/UserGroups.pm \
	  lib/CAP/Schema/Result/InstitutionCollection.pm blib/lib/CAP/Schema/Result/InstitutionCollection.pm \
	  lib/CAP/Schema/ResultSet/UserRole.pm blib/lib/CAP/Schema/ResultSet/UserRole.pm \
	  lib/CAP/Schema/ResultSet/UserCollection.pm blib/lib/CAP/Schema/ResultSet/UserCollection.pm \
	  lib/CAP/View/Test.pm blib/lib/CAP/View/Test.pm \
	  lib/CAP/Controller/Search.pm blib/lib/CAP/Controller/Search.pm \
	  lib/CAP/Controller/Admin.pm blib/lib/CAP/Controller/Admin.pm \
	  lib/BagIt.pm blib/lib/BagIt.pm \
	  lib/CAP/View/Dojo.pm blib/lib/CAP/View/Dojo.pm \
	  lib/CAP/Schema/Result/Sessions.pm blib/lib/CAP/Schema/Result/Sessions.pm \
	  lib/CAP/Schema/Result/UserRole.pm blib/lib/CAP/Schema/Result/UserRole.pm \
	  lib/CAP/Controller/Foo.pm blib/lib/CAP/Controller/Foo.pm \
	  lib/CAP.pm blib/lib/CAP.pm \
	  lib/CAP/Schema/Result/UserCollection.pm blib/lib/CAP/Schema/Result/UserCollection.pm \
	  lib/CAP/I18N/fr.mo blib/lib/CAP/I18N/fr.mo \
	  lib/CAP/View/Mail.pm blib/lib/CAP/View/Mail.pm \
	  lib/CAP/Schema/ResultSet/Labels.pm blib/lib/CAP/Schema/ResultSet/Labels.pm \
	  lib/CAP/Schema/ResultSet/SearchLog.pm blib/lib/CAP/Schema/ResultSet/SearchLog.pm \
	  lib/CAP/Schema/ResultSet/InstitutionIpaddr.pm blib/lib/CAP/Schema/ResultSet/InstitutionIpaddr.pm \
	  lib/CAP/Model/DB.pm blib/lib/CAP/Model/DB.pm \
	  lib/CAP/Schema/Result/Promocode.pm blib/lib/CAP/Schema/Result/Promocode.pm \
	  lib/CAP/Controller/Payment/PayPal.pm blib/lib/CAP/Controller/Payment/PayPal.pm \
	  lib/CAP/Schema/Result/Groups.pm blib/lib/CAP/Schema/Result/Groups.pm \
	  lib/CAP/Schema/Result/Info.pm blib/lib/CAP/Schema/Result/Info.pm \
	  lib/CAP/Schema/Result/SearchLog.pm blib/lib/CAP/Schema/Result/SearchLog.pm \
	  lib/CAP/Schema/Result/InstitutionIpaddr.pm blib/lib/CAP/Schema/Result/InstitutionIpaddr.pm \
	  lib/CAP/Schema/Result/GroupsCollection.pm blib/lib/CAP/Schema/Result/GroupsCollection.pm \
	  lib/CAP/Schema/ResultSet/Collection.pm blib/lib/CAP/Schema/ResultSet/Collection.pm \
	  lib/CAP/Controller/View.pm blib/lib/CAP/Controller/View.pm \
	  lib/CAP/Schema/ResultSet/Sessions.pm blib/lib/CAP/Schema/ResultSet/Sessions.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
# Postamble by Module::Install 0.91
# --- Module::Install::Admin::Makefile section:

realclean purge ::
	$(RM_F) $(DISTVNAME).tar$(SUFFIX)
	$(RM_F) MANIFEST.bak _build
	$(PERL) "-Ilib" "-MModule::Install::Admin" -e "remove_meta()"
	$(RM_RF) inc

reset :: purge

upload :: test dist
	cpan-upload -verbose $(DISTVNAME).tar$(SUFFIX)

grok ::
	perldoc Module::Install

distsign ::
	cpansign -s

catalyst_par :: all
	$(NOECHO) $(PERL) -Ilib -Minc::Module::Install -MModule::Install::Catalyst -e"Catalyst::Module::Install::_catalyst_par( '', 'CAP', { CLASSES => [], CORE => 0, ENGINE => 'CGI', MULTIARCH => 0, SCRIPT => '', USAGE => q## } )"
# --- Module::Install::AutoInstall section:

config :: installdeps
	$(NOECHO) $(NOOP)

checkdeps ::
	$(PERL) Makefile.PL --checkdeps

installdeps ::
	$(NOECHO) $(NOOP)

