#!/bin/bash

# This script will dump the content, other than user information (i.e.
# portals, titles, institutions and institutional subscriptions) from the
# CAP database. Log data isn't dumped. Normally, this would be run from
# production to create a snapshot of content that can be exported to other
# servers (dev/test/local developer).

mysqldump -u root -p cap \
    collection \
    contributor \
    discounts \
    documents \
    institution \
    institution_alias \
    institution_ipaddr \
    institution_mgmt \
    institution_subscription \
    labels \
    language \
    media_type \
    pages \
    portal \
    portal_collection \
    portal_feature \
    portal_host \
    portal_lang \
    portal_string \
    portal_subscription \
    portal_support \
    portals_titles \
    promocode \
    slide \
    slide_description \
    terms \
    titles \
    titles_terms \
> cap_content.sql


