#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
my $config_file = "$FindBin::Bin/../../CAP/cap.conf";
my $post = "$FindBin::Bin/post.pl";


my $batch_files = 12000; # maximum number of files per batch
my $batch_filesize = 50; # maximum file size (MB) per batch.

my @files = ();
my $filesize = 0;
$batch_filesize = $batch_filesize * 1024 * 1024; # Convert to bytes
while (my $file = <STDIN>) {
    chomp($file);
    push(@files, $file);
    $filesize += (stat($file))[7];
    ingest_batch() if (int(@files) >= $batch_files || $filesize >= $batch_filesize);
}
ingest_batch() if (int(@files));

sub ingest_batch
{
    my $time_start = time();
    printf("Ingesting batch of %d files (%d MB).\n", int(@files), $filesize / 1024 / 1024);
    system($post,  "--cmr", "--conf", $config_file, @files);
    my $time_end = time();
    my $time_elapsed = $time_end - $time_start + 1;
    printf(
        "Batch ingested in %d seconds (%4.1f files/second; %d bytes/second)\n",
        $time_elapsed, @files / $time_elapsed, $filesize / $time_elapsed
    );
    @files = ();
    $filesize = 0;
}
