=head1 Upgrading An Installation

=over 4

=item untar the distribution file: tar zxf cap-$version.tgz

=item stop the webserver: apachectl stop

=item change the cap symlink to point to the new distribution: rm cap; ln
-s cap-$version cap

=item go into cap/CAP/script and make the files executable (chmod 755 *)

=item update the config file as needed

=item restart the webserver: apachectl start

=back

